import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const myFont = localFont({
  src: [
    {
      path: "./fonts/HelveticaNeueLTProBlkExO.otf",
      weight: "900",
      style: "black",
    },
    {
      path: "./fonts/HelveticaNeueLTProBlk.otf",
      weight: "700",
      style: "bold",
    },
    {
      path: "./fonts/HelveticaNeueLTProBd.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/HelveticaNeueLTProCn.otf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--Italic-black",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${myFont.className} bg-white overflow-x-hidden`}>{children}</body>
    </html>
  );
}
